runtime: python39  # Use Python 3.9 runtime (or another appropriate version)
instance_class: F2  # Standard instance class (adjust based on your needs)

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

# Environment variables
env_variables:
  ENV: 'production'
  ALLOWED_HOSTS: '*'

# Handlers for static files (if needed)
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
